#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"
UTIL_DIR="$HOME/.config/sketchybar/util"
EXT_DIR="$HOME/.config/sketchybar/ext"
ITEM_DIR="$HOME/.config/sketchybar/items"

SPACE_ID=$(echo "$INFO" | jq -r '."display-1"')

bar=(
    height=34
    color=0x00000000
    margin=30
    sticky=on
    y_offset=4
    notch_width=220
    display=main
    blur_radius=30
    corner_radius=7
    padding_left=4
    padding_right=0
)

defaults=(
    background.color=0x66494d64
    background.corner_radius=5
    background.padding_right=5
    background.height=26
    icon.font="$FONT_FACE:Medium:15.0"
    icon.padding_left=5
    icon.padding_right=5
    label.font="$FONT_FACE:Medium:12.0"
    label.color=0xffcad3f5
    label.y_offset=0
    label.padding_left=0
    label.padding_right=5
)

current_space=(
    current_space
    background.color=0xfff5a97f
    icon.color=0xff24273a
    label.drawing=off
    script="$PLUGIN_SHARED_DIR/current_space.sh"
)

front_app=(
    front_app
    background.color=0xffa6da95
    background.padding_left=0
    background.padding_right=0
    icon.y_offset=1
    icon.color=0xff24273a
    label.drawing=noQ
    script="$PLUGIN_SHARED_DIR/front_app.sh"
    click_script="$UTIL_DIR/showbar.sh"
)

front_app_separator=(
    front_app.separator
    background.color=0x00000000
    background.padding_left=-3.9
    icon=
    icon.color=0xffa6da95
    icon.font="$FONT_FACE:Bold:19.5"
    icon.padding_left=0
    icon.padding_right=0
    icon.y_offset=1
    label.drawing=no
    click_script="$UTIL_DIR/showbar.sh"
)

front_app_name=(
    front_app.name
    background.color=0x00000000
    background.padding_right=0
    icon.drawing=off
    label.font="$FONT_FACE:Bold:12.0"
    label.drawing=yes
    click_script="$UTIL_DIR/showbar.sh"
)

media=(
    media
    label.max_chars=70
    label.padding_left=28
    icon.padding_left=0
    scroll_texts=on
    icon.color=0xff8aadf4
    script="$PLUGIN_SHARED_DIR/media.sh"
    click_script="$PLUGIN_SHARED_DIR/media.click.sh"
    background.color=0x00000000
    background.image.drawing=on
    background.image="media.artwork"
    background.image.corner_radius=4
    background.image.padding_left=0
    background.image.scale=0.18
    update_freq=10
)

big_cover=(
    big_cover
    drawing=off
    background.image.corner_radius=10
)

reminders=(
    reminders
    label.max_chars=45
    padding_left=4
    icon.drawing=off
    label.padding_left=4
    label.padding_right=5
    background.color=0x00000000
    script="$PLUGIN_SHARED_DIR/reminders.sh"
    click_script="open -a /System/Applications/Reminders.app"
)

clock=(
    clock
    update_freq=10
    background.color=0x00000000
    icon.color=0xffcad3f5
    icon.font="$FONT_FACE:Bold:12.0"
    label.width=45
    label.align=right
    label.font="$FONT_FACE:Medium:12.0"
    script="$PLUGIN_SHARED_DIR/clock.sh"
    click_script="yabai -m space --focus 9"
)

battery=(
    battery
    update_freq=20
    script="$PLUGIN_SHARED_DIR/battery.sh"
    click_script="$UTIL_DIR/showbar.sh 1570"
)

volume=(
    volume
    icon.color=0xff8aadf4
    label.font="$FONT_FACE:Medium:12.0"
    script="$PLUGIN_SHARED_DIR/volume.sh"
)

vpn=(
    vpn
    icon.color=0xff8aadf4
    label.font="$FONT_FACE:Medium:12.0"
    script="$PLUGIN_SHARED_DIR/vpn.sh"
    click_script="/Users/gleblevkov/workflow/sfera-user-login/sfera-user-login.sh gen --clean test1 | pbcopy"
    update_freq=20
)

keyboard=(
    keyboard
    icon.drawing=off
    label.font="$FONT_FACE:Medium:12.0"
    label.padding_left=6
    label.y_offset=0
    label.padding_right=6
    script="$PLUGIN_SHARED_DIR/keyboard.sh"
)

weather=(
    weather
    icon.drawing=off
    update_freq=1800
    background.color=0x00000000
    script="$PLUGIN_SHARED_DIR/weather.sh"
)

sketchybar \
    --bar "${bar[@]}" \
    --default "${defaults[@]}" \
    --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
    --add event now_playing_change \
    --add item current_space left --set "${current_space[@]}" --subscribe current_space space_change mouse.clicked \
    --add item front_app left --set "${front_app[@]}" \
    --add item front_app.separator left --set "${front_app_separator[@]}" \
    --add item front_app.name left --set "${front_app_name[@]}" \
    --add item media q --set "${media[@]}" --subscribe media now_playing_change mouse.clicked \
    --add item big_cover popup.media --set "${big_cover[@]}" \
    --add item reminders e --set "${reminders[@]}" --subscribe reminders front_app_switched \
    --add bracket front_app_bracket front_app front_app.separator front_app.name --subscribe front_app front_app_switched \
    --add item clock right --set "${clock[@]}" \
    --add item battery right --set "${battery[@]}" \
    --add item volume right --set "${volume[@]}" --subscribe volume volume_change \
    --add item keyboard right --set "${keyboard[@]}" --subscribe keyboard keyboard_change \
    --add item vpn right --set "${vpn[@]}" \
    --add item weather right --set "${weather[@]}" \
    --add event keyboard_change "AppleSelectedInputSourcesChangedNotification" \
    --update \
    --trigger space_change

# extensions
if ! pgrep -f "mediaplayer_watcher" > /dev/null; then
    ~/workflow/media-control-subscriber/mediaplayer_watcher &
    echo "Run: mediaplayer_watcher"
fi